---
# https://github.com/AlexNabokikh/windows-playbook/blob/master/tasks/start_menu.yml
- name: Disable Automatic Install of Suggested Apps.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SilentInstalledAppsEnabled
    data: 0
    type: dword
  become: true
  become_method: runas
  become_user: '{{ Comp_User }}'

- name: Disable App Suggestions in Start menu.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SystemPaneSuggestionsEnabled
    data: 0
    type: dword
  become: true
  become_method: runas
  become_user: '{{ Comp_User }}'

- name: Disable popup "tips" about Windows.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SoftLandingEnabled
    data: 0
    type: dword
  become: true
  become_method: runas
  become_user: '{{ Comp_User }}'

- name: Disable 'Windows Welcome Experience'.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - SubscribedContent-310093Enabled
    - SubscribedContent-338388Enabled
    - SubscribedContent-338389Enabled
    - SubscribedContent-88000326Enabled
  become: true
  become_method: runas
  become_user: '{{ Comp_User }}'