---
- name: Copy htp.jpg to C:\
  ansible.windows.win_copy:
    src: htp.jpg
    dest: C:\

- name: Create Registry Key to apply Wallpaper
  win_regedit:
    key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    value: Wallpaper
    data: C:\htp.jpg
  become: true
  become_method: runas
  become_user: '{{ Comp_User }}'

- name: Create Registry Key to apply Wallpaper style
  win_regedit:
    key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    value: WallpaperStyle
    data: 4
  become: true
  become_method: runas
  become_user: '{{ Comp_User }}'